/**
 * Security and Input Sanitization Utilities
 * Defends against Prototype Pollution, ReDoS payload injection, and untrusted input anomalies.
 */

const FORBIDDEN_KEYS = new Set(['__proto__', 'constructor', 'prototype']);

/**
 * Checks if a property key is safe to access or set
 */
export function isSafePropertyKey(key: string): boolean {
  if (!key || typeof key !== 'string') return false;
  const trimmed = key.trim();
  if (FORBIDDEN_KEYS.has(trimmed)) return false;
  if (trimmed.startsWith('__')) return false;
  return true;
}

/**
 * Recursively sanitizes any untrusted object or array, stripping __proto__,
 * constructor, and prototype keys, and capping excessively long string values
 * to protect against ReDoS and memory bloat.
 */
export function deepSanitizeUntrustedObject<T = any>(input: T, maxDepth = 20, currentDepth = 0): T {
  if (currentDepth > maxDepth) {
    return null as any;
  }

  if (input === null || typeof input !== 'object') {
    if (typeof input === 'string' && input.length > 500000) {
      // Cap individual strings to 500KB to mitigate memory exhaustion
      return input.slice(0, 500000) as any;
    }
    return input;
  }

  if (Array.isArray(input)) {
    const sanitizedArray: any[] = [];
    for (let i = 0; i < input.length; i++) {
      sanitizedArray.push(deepSanitizeUntrustedObject(input[i], maxDepth, currentDepth + 1));
    }
    return sanitizedArray as any;
  }

  // Plain object
  const cleanObj: Record<string, any> = {};
  const entries = Object.entries(input as Record<string, any>);

  for (const [key, value] of entries) {
    if (!isSafePropertyKey(key)) {
      continue;
    }
    cleanObj[key] = deepSanitizeUntrustedObject(value, maxDepth, currentDepth + 1);
  }

  return cleanObj as T;
}

/**
 * Safely parses untrusted JSON strings with a prototype-stripping reviver
 * and subsequent deep object sanitization.
 */
export function safeJsonParse<T = any>(jsonString: string): T {
  if (typeof jsonString !== 'string') {
    throw new Error('Input is not a string');
  }

  // Safe reviver to catch __proto__, constructor, and prototype before object instantiation
  const parsed = JSON.parse(jsonString, (key, value) => {
    if (key === '__proto__' || key === 'constructor' || key === 'prototype') {
      return undefined;
    }
    return value;
  });

  return deepSanitizeUntrustedObject(parsed);
}

/**
 * Sanitizes raw tabular row objects generated by xlsx (sheet_to_json)
 * to ensure all columns and values are prototype-safe primitives.
 */
export function sanitizeExcelSheetRow(rawRow: any): Record<string, any> {
  if (!rawRow || typeof rawRow !== 'object') return {};

  const cleanRow: Record<string, any> = {};
  for (const key of Object.keys(rawRow)) {
    if (!isSafePropertyKey(key)) continue;

    const val = rawRow[key];
    if (val === null || val === undefined) {
      cleanRow[key] = '';
    } else if (typeof val === 'string') {
      // Strip dangerous characters and cap length
      cleanRow[key] = val.slice(0, 2000).trim();
    } else if (typeof val === 'number') {
      cleanRow[key] = isNaN(val) ? 0 : val;
    } else if (typeof val === 'boolean') {
      cleanRow[key] = val;
    } else {
      cleanRow[key] = String(val).slice(0, 2000).trim();
    }
  }

  return cleanRow;
}
